Add Amplitude feature setUserProperties
rorygarand/react-amplitude pull request #4
Opened 2018-01-26 20:10 UTC by chasedut

Looking to add support for setting Amplitude user properties, which is already made available in the initialize function

see initialize here: 
![screen shot 2018-01-26 at 12 07 43 pm](https://user-images.githubusercontent.com/13496464/35458545-a2e4695a-0291-11e8-8a4a-ba636c4a08ba.png)

docs below on setUserProperties:

https://amplitude.zendesk.com/hc/en-us/articles/207108327-Step-4-Set-User-Properties-and-Event-Properties

https://amplitude.zendesk.com/hc/en-us/articles/115001361248-JavaScript-SDK-Installation#setting-multiple-user-properties

2018-01-27 00:54 UTC, timurista approved these changes
Nice, LGTM!

2018-01-27 01:16 UTC, boxman0617 requested changes
Just one quick request.

2018-01-27 01:16 UTC, boxman0617 commented on src/index.js
> +    console.log('amplitude userProps...');
Can you wrap this in `_debug` and use `log()` instead? Look at some of the examples above in method: `amplitude`

2018-01-27 01:21 UTC, boxman0617 commented on src/index.js
> +    console.log('amplitude userProps...');
or remove it?

2018-01-29 15:18 UTC, rorygarand commented
@chasedut @timurista @boxman0617 thanks!

i have some other changes i need to get merged in today, but this will go in right afterwards.

2018-01-29 18:53 UTC, boxman0617 approved these changes
LGTM!

2018-01-29 22:03 UTC, rorygarand approved these changes

2018-01-29 22:03 UTC, merged